export const JWT_CONFIGS = {
  JWT_ALGORITHM: process.env.JWT_ALGORITHM,
  SECRET_KEY_JWT: process.env.SECRET_KEY_JWT,
  TIME_EXPIRE_ACCESS_TOKEN: process.env.TIME_EXPIRE_ACCESS_TOKEN,
  TIME_EXPIRE_REFRESH_TOKEN: process.env.TIME_EXPIRE_REFRESH_TOKEN
};
